academycity/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView


urlpatterns = [
    path('acauth/', include('apps.acauth.urls')),
    path('', include('apps.index.urls')),
    path('tinymce/', include('apps.tinymce.urls')),
    path('student/', include('apps.student.urls')),
    path('course/', include('apps.course.urls')),
    # 网站图标
    path('favicon.ico', RedirectView.as_view(url='/static/images/favicon.min.ico')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/course/urls.py
from django.urls import path
from . import views

app_name = 'course'

urlpatterns = [
    path('publish_course/', views.publish_course_view, name='publish_course'),
    path('select_school_course/', views.select_school_course, name='select_school_course'),
    path('add_course/', views.add_course, name='add_course'),
    path('time_table/', views.TimeTable.as_view(), name='time_table'),
    path('select_course/', views.select_course, name='select_course'),
    path('submit_event/', views.submit_event, name='submit_event'),
    path('course_list/<school_id>/', views.course_list_view, name='course_list'),
    path('course_score/<course_id>/', views.CourseScoreView.as_view(), name='course_score'),
]

apps/course/models.py
from django.db import models


class WeekDay(models.Model):
    name = models.CharField(max_length=4)


class CourseTime(models.Model):
    name = models.CharField(max_length=50)


class Course(models.Model):
    name = models.CharField(max_length=20)
    week_day = models.ForeignKey('WeekDay', on_delete=models.DO_NOTHING, null=True)
    course_time = models.ForeignKey('CourseTime', on_delete=models.DO_NOTHING, null=True)
    school = models.ManyToManyField('index.School')
    student = models.ManyToManyField('acauth.User', through='Score')

    class Meta:
        ordering = ['week_day', 'course_time']


class Score(models.Model):
    student = models.ForeignKey('acauth.User', on_delete=models.DO_NOTHING)
    course = models.ForeignKey('Course', on_delete=models.DO_NOTHING)
    score = models.FloatField(null=True)

apps/course/views.py
import json
from django.shortcuts import render
from django.views.decorators.http import require_POST
from utils import restful
from .models import Course, WeekDay, CourseTime, Score
from apps.index.models import School
from django.http import Http404
from django.views import View
from .serializers import CourseSerializer
from django.contrib.auth import get_user_model

User = get_user_model()


def publish_course_view(request):
    school = request.user.school
    if school:
        courses = Course.objects.select_related('week_day', 'course_time').all()
        weekdays = WeekDay.objects.all()
        course_times = CourseTime.objects.all()
        context = {
            'courses': courses,
            'weekdays': weekdays,
            'course_times': course_times,
        }
        return render(request, 'course/publish_course.html', context=context)
    else:
        raise Http404


@require_POST
def select_school_course(request):
    school_id = request.POST.get('school_id')
    course_ids = json.loads(request.POST.get('course_ids'))
    school = School.objects.get(pk=school_id)
    school.course_set.set(course_ids)
    school.save()
    return restful.ok()


@require_POST
def add_course(request):
    name = request.POST.get('course_name')
    week_day_id = request.POST.get('week_day_id')
    course_time_id = request.POST.get('course_time_id')
    week_day = WeekDay.objects.get(pk=week_day_id)
    course_time = CourseTime.objects.get(pk=course_time_id)
    course = Course.objects.create(name=name, week_day=week_day, course_time=course_time)
    return restful.result(code=200, data={
        'week_day': week_day.name,
        'course_time': course_time.name,
        'id': course.pk,
    })


class TimeTable(View):
    def get(self, request):
        user = request.user
        school = user.school
        school_courses = school.course_set.all()
        user_courses = user.course_set.all()
        course_times = CourseTime.objects.all()
        mon = []
        tue = []
        wed = []
        thu = []
        fri = []
        weeks = [mon, tue, wed, thu, fri]
        course_type = []
        for i in weeks:
            for j in range(1, 5):
                try:
                    i.append(user_courses.filter(week_day_id=weeks.index(i)+1).filter(course_time_id=j).first().name)
                except:
                    i.append('')
        weeks = json.dumps(weeks)
        for course_time in course_times:
            course_type.append([{'index': course_time.pk, 'name': course_time.name}, 1])
        course_type = json.dumps(course_type)
        context = {
            'user_courses': user_courses,
            'school_courses': school_courses,
            'weeks': weeks,
            'course_type': course_type,
        }
        return render(request, 'course/time_table.html', context=context)


@require_POST
def select_course(request):
    school = request.user.school
    school_courses = school.course_set.all()
    week = request.POST.get('week')  # 周几
    index = request.POST.get('index')  # 第几节课
    week_day = WeekDay.objects.get(name=week)
    course_time = CourseTime.objects.get(pk=index)
    current_courses = school_courses.filter(week_day=week_day, course_time=course_time)
    serializer = CourseSerializer(current_courses, many=True)
    return restful.result(data=serializer.data)


@require_POST
def submit_event(request):
    course_id = int(request.POST.get('course_id'))
    week_name = request.POST.get('week')
    course_time = request.POST.get('course_time')
    week_day = WeekDay.objects.get(name=week_name)
    course_time = CourseTime.objects.get(pk=course_time)
    if course_id != 0:
        course = Course.objects.get(pk=course_id)
        Score.objects.filter(course__week_day=week_day, course__course_time=course_time, student=request.user).delete()
        Score.objects.create(student=request.user, course=course)
    else:
        Score.objects.filter(course__week_day=week_day, course__course_time=course_time, student=request.user).delete()
    return restful.ok()


def course_list_view(request, school_id):
    school = School.objects.get(pk=school_id)
    courses = Course.objects.filter(school=school)
    context = {
        'courses': courses
    }
    return render(request, 'course/course_list.html', context=context)


class CourseScoreView(View):
    def get(self, request, course_id):
        school = request.user.school
        course = Course.objects.get(pk=course_id)
        students = User.objects.filter(school=school, course=course)
        scores = Score.objects.select_related('student').filter(student__in=students, course=course)
        context = {
            'scores': scores,
            'course': course,
        }
        return render(request, 'course/course_score.html', context=context)

    def post(self, request, course_id):
        student_id = request.POST.get('studentId')
        student = User.objects.get(pk=student_id)
        course = Course.objects.get(pk=course_id)
        score = request.POST.get('score')
        Score.objects.filter(student=student, course=course).update(score=score)
        return restful.ok()

front/templates/course/course_list.html
{% extends 'common/base.html' %}

{% block title %}
    课程列表
{% endblock %}

{% block head %}

{% endblock %}

{% block content-header %}
    <strong>Academy</strong>CITY | Course List
{% endblock %}

{% block content %}
    <div class="card card-solid">
        <div class="card-body pb-0">
            <div class="row d-flex align-items-stretch">
                {% for course in courses %}
                    <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch" style="margin-bottom: 20px;">
                        <a href="{% url 'course:course_score' course.pk %}" class="btn btn-default btn-block">{{ course.name }}</a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

front/templates/course/course_score.html
{% extends 'common/base.html' %}

{% block title %}
    成绩录入
{% endblock %}

{% block head %}
    <script src="{% static 'js/course_score.min.js' %}"></script>
    <script type="text/javascript">
        function showButton(node) {
            var confirmBtn = node.parentNode.nextElementSibling.firstChild;
            confirmBtn.removeAttribute("hidden");
        }
    </script>
{% endblock %}

{% block content-header %}
    <strong>Academy</strong>CITY | Score Entry
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card card-solid">
                    <div class="card-header">
                        <h3>{{ course.name }} | 成绩录入</h3>
                    </div>
                    <div class="card-body">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>学生编号</th>
                                    <th>学生姓名</th>
                                    <th>本科成绩</th>
                                    <th>操作</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for score in scores %}
                                    <tr>
                                        <td class="student-uid">{{ score.student.uid }}</td>
                                        <td class="student-name">{{ score.student.username }}</td>
                                        <td class="score"><input type="number" value="{{ score.score }}" class="form-control" onchange="showButton(this)"></td>
                                        <td><button hidden class="confirm btn btn-block btn-primary" data-course-id="{{ course.pk }}">确定</button></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

front/templates/course/publish_course.html
{% extends 'common/base.html' %}

{% block title %}
    发布课程
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'adminlte/plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css' %}">
    <script src="{% static 'adminlte/plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.min.js' %}"></script>
    <script src="{% static 'js/publish_course.min.js' %}"></script>
{% endblock %}

{% block content-header %}
    <strong>Academy</strong>CITY | Publish Course
{% endblock %}

{% block content %}
    <div class="card card-default">
        <div class="card-header">
            <h3 class="card-title">课程选择</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i>
                </button>
            </div>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-12">
                    <div class="form-group">
                        <button class="btn btn-primary" data-toggle="modal" data-target="#course-modal">添加课程</button>
                        <select class="duallistbox" multiple="multiple" style="height: 200px;">
                            {% for course in courses %}
                                {% if course in user.school.course_set.all %}
                                    <option value="{{ course.pk }}" selected>{{ course.name }}&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;&nbsp;&nbsp;&nbsp;{{ course.week_day.name }}&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;&nbsp;&nbsp;&nbsp;{{ course.course_time.name }}</option>
                                {% else %}
                                    <option value="{{ course.pk }}">{{ course.name }}&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;&nbsp;&nbsp;&nbsp;{{ course.week_day.name }}&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;&nbsp;&nbsp;&nbsp;{{ course.course_time.name }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                    <!-- /.form-group -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            <button class="btn btn-primary float-right define-btn" data-school-id="{{ user.school_id }}">确定</button>
        </div>
    </div>
{% endblock %}

{% block endfooter %}
    <div class="modal fade" id="course-modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            <label for="course-input" class="col-form-label">课程名称</label>
                            <input type="text" class="form-control" id="course-input">
                        </div>
                        <div class="form-group">
                            <label for="weekday-input" class="col-form-label">上课日期</label>
                            <select class="form-control" name="weekday" id="weekday-input">
                                {% for weekday in weekdays %}
                                    <option value="{{ weekday.pk }}">{{ weekday.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="time-inpt" class="col-form-label">上课时间</label>
                            <select class="form-control" name="time" id="time-input">
                                {% for course_time in course_times %}
                                    <option value="{{ course_time.pk }}">{{ course_time.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary submit-btn">确定</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

front/templates/course/time_table.html
{% extends 'common/base.html' %}

{% block title %}
    课程表
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/course/time_table.min.css' %}">
    <script src="{% static 'js/Timetables.min.js' %}"></script>
    <script src="{% static 'js/time_table.min.js' %}"></script>
    <script src="{% static 'arttemplate/template-web.js' %}"></script>
    <script id="course-item" type="text/html">
    {% verbatim %}
        <option value="0">取消本节课</option>
        {{ each school_courses school_course index }}
            {{ if course_name == school_course.name }}
                <option value="{{ school_course.id }}" selected>{{ school_course.name }}</option>
            {{ else }}
                <option value="{{ school_course.id }}">{{ school_course.name }}</option>
            {{ /if }}
        {{ /each }}
    {% endverbatim %}
    </script>
{% endblock %}

{% block content-header %}
    <strong>Academy</strong>CITY | Class Schedule
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <h3>点击方块进行选课</h3>
                {% if user.school %}
                    <div id="coursesTable" data-weeks="{{ weeks }}" data-course-type="{{ course_type }}"></div>
                {% else %}
                    <span>您还未加入任何学校！</span>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

{% block endfooter %}
    <div class="modal fade" id="course-modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            <label for="course-input" class="col-form-label">选择课程</label>
                            <select id="course-input" class="form-control">
                            </select>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary submit-btn">确定</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}