academycity/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView


urlpatterns = [
    path('acauth/', include('apps.acauth.urls')),
    path('', include('apps.index.urls')),
    path('tinymce/', include('apps.tinymce.urls')),
    path('student/', include('apps.student.urls')),
    path('course/', include('apps.course.urls')),
    # 网站图标
    path('favicon.ico', RedirectView.as_view(url='/static/images/favicon.min.ico')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/acauth/urls.py
from django.urls import path
from . import views

app_name = 'acauth'

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('register/', views.Register.as_view(), name='register'),
    path('img_captcha/', views.image_captcha, name='img_captcha'),
    # path('operate_group/', views.operate_group, name='operate_group'),
    path('upload_avatar/', views.upload_avatar, name='upload_avatar'),
    path('logout/', views.logout_view, name='logout'),
]

apps/course/urls.py
from django.urls import path
from . import views

app_name = 'course'

urlpatterns = [
    path('publish_course/', views.publish_course_view, name='publish_course'),
    path('select_school_course/', views.select_school_course, name='select_school_course'),
    path('add_course/', views.add_course, name='add_course'),
    path('time_table/', views.TimeTable.as_view(), name='time_table'),
    path('select_course/', views.select_course, name='select_course'),
    path('submit_event/', views.submit_event, name='submit_event'),
    path('course_list/<school_id>/', views.course_list_view, name='course_list'),
    path('course_score/<course_id>/', views.CourseScoreView.as_view(), name='course_score'),
]

apps/index/urls.py
from django.urls import path
from . import views

app_name = 'index'

urlpatterns = [
    path('', views.index, name='index'),
    path('school_list/', views.SchoolList.as_view(), name='school_list'),
    path('school_level/', views.school_level_view, name='school_level'),
    path('add_school/', views.AddSchool.as_view(), name='add_school'),
    path('edit_school/', views.EditSchool.as_view(), name='edit_school'),
    path('del_school/', views.del_school, name='del_school'),
    path('school_detail/<int:school_id>', views.school_detail, name='school_detail'),
    path('add_school_level/', views.add_school_level, name='add_school_level'),
    path('edit_school_level/', views.edit_school_level, name='edit_school_level'),
    path('del_school_level/', views.del_school_level, name='del_school_level'),
    path('upload_badge/', views.upload_badge_view, name='upload_badge'),
    path('join_school/', views.join_school_view, name='join_school'),
    path('quit_school/', views.quit_school_view, name='quit_school'),
    path('add_comment/', views.add_comment_view, name='add_comment_view'),
    path('director_list/', views.DirectorList.as_view(), name='director_list'),
    path('del_director/', views.del_director, name='del_director'),
    path('add_message/', views.add_message, name='add_message'),
    path('agree_apply_level/', views.agree_apply_level, name='agree_apply_level'),
    path('agree_apply_director/', views.agree_apply_director, name='agree_apply_director'),
    path('del_message/', views.del_message, name='del_message'),
]

apps/student/urls.py
from django.urls import path
from . import views

app_name = 'student'

urlpatterns = [
    path('student_list/', views.StudentsListView.as_view(), name='student_list'),
    path('del_student_school/', views.del_student, name='del_student_school'),
    path('student_score/', views.student_score, name='student_score'),
]

front/templates/common/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %} | 学园都市</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'adminlte/plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Ionicons -->
    {#  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">#}
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet"
          href="{% static 'adminlte/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{% static 'adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
    <!-- JQVMap -->
{#    <link rel="stylesheet" href="{% static 'adminlte/plugins/jqvmap/jqvmap.min.css' %}">#}
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/adminlte.min.css' %}">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{% static 'adminlte/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{% static 'adminlte/plugins/daterangepicker/daterangepicker.css' %}">
    <!-- summernote -->
    <link rel="stylesheet" href="{% static 'adminlte/plugins/summernote/summernote-bs4.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    <!-- jQuery -->
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="{% static 'adminlte/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- ChartJS -->
    <script src="{% static 'adminlte/plugins/chart.js/Chart.min.js' %}"></script>
    <!-- Sparkline -->
    <script src="{% static 'adminlte/plugins/sparklines/sparkline.js' %}"></script>
    <!-- JQVMap -->
{#    <script src="{% static 'adminlte/plugins/jqvmap/jquery.vmap.min.js' %}"></script>#}
{#    <script src="{% static 'adminlte/plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>#}
    <!-- jQuery Knob Chart -->
    <script src="{% static 'adminlte/plugins/jquery-knob/jquery.knob.min.js' %}"></script>
    <!-- daterangepicker -->
    <script src="{% static 'adminlte/plugins/moment/moment.min.js' %}"></script>
    <script src="{% static 'adminlte/plugins/daterangepicker/daterangepicker.js' %}"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="{% static 'adminlte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
    <!-- Summernote -->
    <script src="{% static 'adminlte/plugins/summernote/summernote-bs4.min.js' %}"></script>
    <!-- overlayScrollbars -->
    <script src="{% static 'adminlte/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
    <!-- Adminlte App -->
    <script src="{% static 'adminlte/dist/js/adminlte.js' %}"></script>
    <!-- Adminlte dashboard demo (This is only for demo purposes) -->
{#    <script src="{% static 'adminlte/dist/js/pages/dashboard.js' %}"></script>#}
    <!-- Adminlte for demo purposes -->
{#    <script src="{% static 'adminlte/dist/js/demo.js' %}"></script>#}
    <!-- ajax -->
    <script src="{% static 'js/acajax.min.js' %}"></script>
    <!-- Sweetalter -->
    <script src="{% static 'js/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/acalert.min.js' %}"></script>
    <!-- base -->
    <script src="{% static 'js/base.min.js' %}"></script>
    {% block head %}{% endblock %}
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a href="{% url 'index:index' %}" class="nav-link">首页</a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a href="{% url 'acauth:logout' %}" class="nav-link">退出登录</a>
            </li>
        </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-light-lightblue elevation-4">
        <!-- Brand Logo -->
        <a href="#" class="brand-link">
            <img src="{% static 'images/ac_logo.min.png' %}" alt="AcademyCity logo"
                 class="brand-image img-circle elevation-3"
                 style="opacity: .8">
            <span class="brand-text font-weight-light"><b>Academy</b>CITY</span>
        </a>

        <!-- Sidebar -->
        <div class="sidebar">
            <!-- Sidebar user panel (optional) -->
            <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                <div class="image">
                    <img src="{{ user.avatar }}" class="img-circle elevation-2"
                         alt="User Image" style="height: 33px; width: 33px">
                </div>
                <div class="info">
                    <a href="#" class="d-block">{{ user.username }}</a>
                </div>
            </div>

            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                    data-accordion="false">
                    <!-- Add icons to the links using the .nav-icon class
                         with font-awesome or any other icon font library -->
                    <li class="nav-item">
                        <a href="{% url 'index:index' %}" class="nav-link">
                            <i class="nav-icon fas fa-home"></i>
                            <p>
                                首页
                            </p>
                        </a>
                    </li>
                    <li class="nav-item has-treeview">
                        <a href="javascript: void(0);" class="nav-link">
                            <i class="nav-icon fas fa-newspaper"></i>
                            <p>
                                校级管理
                                <i class="fas fa-angle-left right"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{% url 'index:add_school' %}" class="nav-link">
                                    <i class="nav-icon fas fa-edit"></i>
                                    <p>
                                        校园注册
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'index:school_level' %}" class="nav-link">
                                    <i class="nav-icon fas fa-tags"></i>
                                    <p>
                                        科研等级
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'index:school_list' %}" class="nav-link">
                                    <i class="nav-icon fas fa-list "></i>
                                    <p>
                                        校园列表
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'index:director_list' %}" class="nav-link">
                                    <i class="nav-icon fas fa-user-nurse"></i>
                                    <p>
                                        校级管理名单
                                    </p>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item  has-treeview">
                        <a href="javascript: void(0);" class="nav-link">
                            <i class="nav-icon fas fa-users"></i>
                            <p>
                                学生管理
                                <i class="fas fa-angle-left right"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                {% if user.school %}
                                    <a href="{% url 'student:student_list' %}" class="nav-link">
                                {% else %}
                                    <a href="javascript: void(0);" class="nav-link bg-gray disabled">
                                {% endif %}
                                    <i class="nav-icon fas fa-address-book "></i>
                                    <p>
                                        学生名单
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'student:student_score' %}" class="nav-link">
                                    <i class="nav-icon fas fa-pencil-ruler "></i>
                                    <p>
                                        考试成绩
                                    </p>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item has-treeview">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-tv"></i>
                            <p>
                                课程管理
                                <i class="fas fa-angle-left right"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                {% if user.school %}
                                    <a href="{% url 'course:publish_course' %}" class="nav-link">
                                {% else %}
                                    <a href="javascript: void(0);" class="nav-link bg-gray disabled">
                                {% endif %}
                                    <i class="nav-icon fas fa-edit"></i>
                                    <p>
                                        发布课程
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item">
                                {% if user.school %}
                                     <a href="{% url 'course:time_table' %}" class="nav-link">
                                {% else %}
                                     <a href="javascript: void(0);" class="nav-link bg-gray disabled">
                                {% endif %}
                                    <i class="nav-icon fas fa-table"></i>
                                    <p>
                                        课程表
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item">
                                {% if user.school %}
                                    <a href="{% url 'course:course_list' user.school.pk %}" class="nav-link">
                                {% else %}
                                    <a href="javascript: void(0);" class="nav-link bg-gray disabled">
                                {% endif %}
                                    <i class="nav-icon fas fa-pen-fancy"></i>
                                    <p>
                                        成绩录入
                                    </p>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <h1>{% block content-header %}{% endblock %}</h1>
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            {% block content %}
            {% endblock %}
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <footer class="main-footer">
        <strong>Academy</strong>CITY
    </footer>
</div>
<!-- ./wrapper -->
{% block endfooter %}
{% endblock %}
</body>
</html>