academycity/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView


urlpatterns = [
    path('acauth/', include('apps.acauth.urls')),
    path('', include('apps.index.urls')),
    path('tinymce/', include('apps.tinymce.urls')),
    path('student/', include('apps.student.urls')),
    path('course/', include('apps.course.urls')),
    # 网站图标
    path('favicon.ico', RedirectView.as_view(url='/static/images/favicon.min.ico')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/index/urls.py
from django.urls import path
from . import views

app_name = 'index'

urlpatterns = [
    path('', views.index, name='index'),
    path('school_list/', views.SchoolList.as_view(), name='school_list'),
    path('school_level/', views.school_level_view, name='school_level'),
    path('add_school/', views.AddSchool.as_view(), name='add_school'),
    path('edit_school/', views.EditSchool.as_view(), name='edit_school'),
    path('del_school/', views.del_school, name='del_school'),
    path('school_detail/<int:school_id>', views.school_detail, name='school_detail'),
    path('add_school_level/', views.add_school_level, name='add_school_level'),
    path('edit_school_level/', views.edit_school_level, name='edit_school_level'),
    path('del_school_level/', views.del_school_level, name='del_school_level'),
    path('upload_badge/', views.upload_badge_view, name='upload_badge'),
    path('join_school/', views.join_school_view, name='join_school'),
    path('quit_school/', views.quit_school_view, name='quit_school'),
    path('add_comment/', views.add_comment_view, name='add_comment_view'),
    path('director_list/', views.DirectorList.as_view(), name='director_list'),
    path('del_director/', views.del_director, name='del_director'),
    path('add_message/', views.add_message, name='add_message'),
    path('agree_apply_level/', views.agree_apply_level, name='agree_apply_level'),
    path('agree_apply_director/', views.agree_apply_director, name='agree_apply_director'),
    path('del_message/', views.del_message, name='del_message'),
]

apps/index/models.py
from django.db import models
from picklefield.fields import PickledObjectField


class SchoolCategory(models.Model):
    name = models.CharField(max_length=10)


class SchoolLevel(models.Model):
    name = models.CharField(max_length=10)
    priority = models.IntegerField(unique=True)

    class Meta:
        ordering = ['priority']


class School(models.Model):
    name = models.CharField(max_length=20, error_messages={'required': '请输入学校名称！'})
    school_level = models.ForeignKey('SchoolLevel', on_delete=models.SET_NULL, null=True)
    school_category = models.ForeignKey('SchoolCategory', on_delete=models.SET_NULL, null=True)
    is_super = models.BooleanField()
    school_badge = models.URLField(error_messages={'required': '请传入学校校徽！'})
    location = models.CharField(max_length=50, error_messages={'required': '请输入学校地址！'})
    email = models.EmailField(error_messages={'required': '请输入学校邮箱！'})
    course_des = models.TextField(null=True, error_messages={'required': '请输入主教课程！'})
    desc = models.TextField(error_messages={'required': '请输入学校描述！'})
    reg_time = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        ordering = ['school_level']
        permissions = [
            ('fire_student', '开除学生'),
            ('fire_director', '开除校级管理者'),
        ]


class Comments(models.Model):
    content = models.TextField(max_length=300)
    author = models.ForeignKey('acauth.User', on_delete=models.SET_NULL, null=True)
    pub_time = models.DateTimeField(auto_now_add=True)
    school = models.ForeignKey('School', on_delete=models.CASCADE, null=True)

    class Meta:
        ordering = ['-pub_time']


class TodoListType(models.Model):
    name = models.CharField(max_length=20)


class TodoList(models.Model):
    content = models.CharField(max_length=100)
    type = models.ForeignKey('TodoListType', on_delete=models.DO_NOTHING, null=True)
    sponsor = models.ForeignKey('acauth.User', on_delete=models.DO_NOTHING, null=True)
    pub_time = models.DateTimeField(auto_now_add=True)
    is_done = models.BooleanField(default=False)
    data = PickledObjectField(null=True)

    class Meta:
        ordering = ['-pub_time']

front/templates/index/edit_school.html
{% extends 'common/base.html' %}

{% block title %}
    校园注册
{% endblock %}

{% block head %}
    <script src="{% static 'tinymce/tinymce.min.js' %}"></script>
    <script src="{% static 'js/timymce_init.min.js' %}"></script>
    <script src="{% static 'js/edit_school.min.js' %}"></script>
{% endblock %}

{% block content-header %}
    <strong>Academy</strong>CITY | Edit School
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-lightblue">
                    <div class="card-header">
                        <h3>注册校园！称霸学院都市！</h3>
                    </div>
                    <form role="form">
                        <div class="card-body">
                            <div class="form-group">
                                <label for="school-name">学校名称</label>
                                <input type="text" class="form-control" id="school-name" placeholder="输入名称" {% if school %} value="{{ school.name }}" {% endif %} >
                            </div>
                            <div class="form-group">
                                <label for="school-level">科研等级</label>
                                <select class="form-control" name="school-level" id="school-level">
                                    {% for level in levels %}
                                        <option value="{{ level.pk }}" {% if school.school_level.pk == level.pk %}selected{% endif %}>{{ level.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="school-category">分类</label>
                                <select class="form-control" name="school-category" id="school-category">
                                    {% for category in categories %}
                                        <option value="{{ category.pk }}"{% if school.school_category.pk == category.pk %}selected{% endif %}>{{ category.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="super">超能力院校</label>
                                <select class="form-control" name="super" id="super">
                                    <option value="0" {% if school.is_super == 0 %}selected{% endif %}>否</option>
                                    <option value="1" {% if school.is_super == 1 %}selected{% endif %}>是</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="school-badge">校徽</label>
                                <div class="input-group">
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" id="school-badge">
                                        <label for="school-badge" class="custom-file-label">{% if school %}{{ school.school_badge }}{% endif %}</label>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="school-location">地址</label>
                                <input type="text" class="form-control" id="school-location" placeholder="输入地址" {% if school %}value="{{ school.location }}"{% endif %}>
                            </div>
                            <div class="form-group">
                                <label for="school-email">邮箱</label>
                                <input type="email" class="form-control" id="school-email" placeholder="输入邮箱" {% if school %}value="{{ school.email }}"{% endif %}>
                            </div>
                            <div class="form-group">
                                <label for="school-course">主教课程</label>
                                <input type="text" class="form-control" id="school-course" placeholder="输入名称 以逗号分隔" {% if school %}value="{{ school.course_des }}"{% endif %}>
                            </div>
                            <div class="form-group">
                                <label for="school-desc">校园简介</label>
                                <textarea name="desc" id="school-desc" cols="30" rows="10" class="form-control" placeholder="输入内容...">{% if school %}{{ school.desc | safe }}{% endif %}</textarea>
                            </div>
                        </div>
                    </form>
                    <div class="card-footer">
                        <button type="submit" id="submit-btn" class="btn btn-primary float-right" data-school-id="{{ school.pk }}">提交</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

front/templates/index/index.html
{% extends 'common/base.html' %}

{% load ac_filters %}

{% block title %}
    首页
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/index/index.min.css' %}">
    <script src="{% static 'js/calendar.min.js' %}"></script>
    <script src="{% static 'js/index.min.js' %}"></script>
{% endblock %}

{% block content-header %}
    <strong>Academy</strong>CITY | 学园都市
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <div class="row">
                    <div class="card card-primary card-outline col-8">
                        <div class="card-body box-profile ">
                            <div class="text-center">
                                <img title="更换头像" class="img-thumbnail img-fluid img-circle avatar-img" src="{{ user.avatar }}" alt="">
                                <input type="file" class="avatar-input" accept="image/*" hidden>
                            </div>
                            <h3 class="text-center">{{ user.username }}</h3>
                            <p class="text-muted text-center">{{ user.school.name }} {% if user.is_director %}管理者{% else %}学生{% endif %}</p>
                            <p class="text-muted text-center">{{ user.superpower.name }}</p>
                        </div>
                    </div>
                    <div class="card card-primary card-outline col-4">
                        <div class="card-body">
                            <div class="level-btn">
                                <button class="btn btn-block btn-outline-primary apply-level" data-toggle="modal" data-target="#level-modal">等级申请</button>
                            </div>
                            <br>
                            <div class="director-btn">
                                {% if user.is_director %}
                                    <button title="您已经是管理者！" class="btn btn-block btn-outline-primary disabled">管理申请</button>
                                {% else %}
                                    <button class="btn btn-block btn-outline-primary apply-director">管理申请</button>
                                {% endif %}
                            </div>
                            <br>
                            <div class="school-btn">
                                {% if user.school %}
                                    <a href="{% url 'index:school_detail' user.school.pk %}" class="btn btn-block btn-outline-primary">本校链接</a>
                                {% else %}
                                    <a title="请先加入学校！" href="#" class="btn btn-block btn-outline-primary disabled">本校链接</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                <!-- TO DO List -->
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            <i class="fa fa-clipboard mr-1"></i>
                            To Do List
                        </h3>
                        <!-- tools card -->
                        <div class="card-tools">
                            <button type="button" class="btn btn-sm" data-card-widget="collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                            <button type="button" class="btn btn-sm" data-card-widget="remove">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <ul class="todo-list" data-widget="todo-list">
                            {% for message in messages %}
                                <li>
                                <!-- todo text -->
                                <span class="text"><a class="text-muted" href="javascript: void(0);">{{ message.content }}</a></span>
                                <!-- Emphasis label -->
                                <small class="badge badge-danger"><i class="far fa-clock"></i>{{ message.pub_time | time_since }}</small>
                                <!-- General tools such as edit or delete-->
                                {% if user.is_director %}
                                    {% if message.type.name == 'apply_level' %}
                                        <div class="tools">
                                            <button class="btn btn-sm btn-danger del-message" data-message-id="{{ message.pk }}">拒绝</button>
                                        </div>
                                        <div class="tools">
                                            <button data-sponsor="{{ message.sponsor.uid }}" data-level="{{ message.data.level.pk }}" data-message-id="{{ message.pk }}" class="btn btn-sm btn-success agree_apply_level">同意</button>
                                        </div>
                                    {% elif message.type.name == 'apply_director' %}
                                        <div class="tools">
                                            <button class="btn btn-sm btn-danger del-message" data-message-id="{{ message.pk }}">拒绝</button>
                                        </div>
                                        <div class="tools">
                                            <button data-sponsor="{{ message.sponsor.uid }}" data-message-id="{{ message.pk }}" class="btn btn-sm btn-success agree_apply_director">同意</button>
                                        </div>
                                    {% elif message.type.name == 'message' %}
                                        <div class="tools">
                                            <button class="btn btn-sm btn-danger del-message" data-message-id="{{ message.pk }}">清除</button>
                                        </div>
                                    {% endif %}
                                {% endif %}
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer clearfix">
                        <form action="{% url 'index:add_message' %}" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <input title="不超过100字符" type="text" name="content" class="form-control col-9" placeholder="请输入要发布的消息...">
                                <input type="text" name="type" value="message" hidden>
                                <button type="submit" class="btn btn-info float-right col-2" style="margin-left: 40px;">发布消息</button>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <div class="col-md-6">
                <!-- DONUT CHART -->
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            <i class="fa fa-chart-pie mr-1"></i>
                            Our School Superpower Chart
                        </h3>
                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse"><i
                                    class="fas fa-minus"></i>
                            </button>
                            <button type="button" class="btn btn-tool" data-card-widget="remove"><i
                                    class="fas fa-times"></i></button>
                        </div>
                    </div>
                    <div class="card-body">
                        {% if user.school %}
                            <canvas data-labels="{{ labels }}" data-counts="{{ counts }}" id="donutChart"
                                    style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
                        {% else %}
                            <h1>您还未加入任何学校！</h1>
                        {% endif %}
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
                <!-- Calendar -->
                <div class="card bg-gradient-cyan col-12">
                    <div class="card-header border-0">
                        <h3 class="card-title">
                            <i class="far fa-calendar-alt"></i>
                            Calendar
                        </h3>
                        <!-- tools card -->
                        <div class="card-tools">
                            <button type="button" class="btn bg-gradient-cyan btn-sm" data-card-widget="collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                            <button type="button" class="btn bg-gradient-cyan btn-sm" data-card-widget="remove">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                        <!-- /. tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body pt-0">
                        <!--The calendar -->
                        <div id="calendar" style="width: 100%"></div>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
                <div class="card card-outline">
                    <div class="card-header">
                        <h3 class="card-title">
                            <i class="fa fa-comments mr-1"></i>
                            My Comments
                        </h3>
                        <div class="card-tools">
                            <button type="button" class="btn btn-sm" data-card-widget="collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                            <button type="button" class="btn btn-sm" data-card-widget="remove">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body">
                        {% for comment in user.comments_set.all %}
                            <div class="post">
                                <div class="user-block">
                                    <img src="{{ comment.school.school_badge }}" alt="">
                                    <span class="username">
                                        <a href="{% url 'index:school_detail' comment.school.pk %}">{{ comment.school.name }}</a>
                                    </span>
                                    <span class="description pub-time">{{ comment.pub_time | time_since }}</span>
                                </div>
                                <p>&emsp;&emsp;&emsp;{{ comment.content }}</p>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block endfooter %}
    <div class="modal fade" id="level-modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <span>能力等级申请</span>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            <label for="level-input" class="col-form-label">能力等级</label>
                            <select class="form-control" id="level-input">
                                {% for level in levels %}
                                    {% if user.superpower == level %}
                                        <option value="{{ level.pk }}" selected>{{ level.name }}</option>
                                    {% else %}
                                        <option value="{{ level.pk }}">{{ level.name }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary level-msg-btn">确定</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

front/templates/index/school_list.html
{% extends 'common/base.html' %}
{% load ac_filters %}

{% block title %}
    校园列表
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/index/school_list.min.css' %}">
    <script src="{% static 'js/school_list.min.js' %}"></script>
{% endblock %}

{% block content-header %}
    <strong>Academy</strong>CITY | School List
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <form action="" method="get" class="form-inline">
                            <div class="form-group left-group">
                                <label for="school-input">搜索：</label>
                                {% if school %}
                                    <input type="text" id="school-input" placeholder="关键字" class="form-control" name="school" value="{{ school }}">
                                {% else %}
                                    <input type="text" id="school-input" placeholder="关键字" class="form-control" name="school">
                                {% endif %}
                            </div>
                            <div class="form-group left-group">
                                <label for="level-input">科研等级：</label>
                                <select name="level" id="level-input" class="form-control">
                                    <option value="0">所有等级</option>
                                    {% for level in levels %}
                                        {% if level_id and level_id == level.pk%}
                                            <option value="{{ level.pk }}" selected>{{ level.name }}</option>
                                        {% else %}
                                            <option value="{{ level.pk }}">{{ level.name }}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group left-group">
                                <label for="category-input">分类：</label>
                                <select name="category" id="category-input" class="form-control">
                                    <option value="0" selected>所有分类</option>
                                    {% for category in categories %}
                                        {% if category_id and category_id == category.pk %}
                                            <option value="{{ category.pk }}" selected>{{ category.name }}</option>
                                        {% else %}
                                            <option value="{{ category.pk }}">{{ category.name }}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group search-btn">
                                <button class="btn btn-primary">查询</button>
                            </div>
                            <div class="form-group search-btn">
                                <a href="{% url 'index:school_list' %}">清除查询</a>
                            </div>
                        </form>
                    </div>
                    <div class="card-body">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>学校编号</th>
                                    <th>名称</th>
                                    <th>科研等级</th>
                                    <th>分类</th>
                                    <th>注册时间</th>
                                    <th>超能力院校</th>
                                    <th>操作</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for s_school in schools %}
                                    <tr>
                                    <td>{{ s_school.pk }}</td>
                                    <td><a href="{% url 'index:school_detail' s_school.pk %}">{{ s_school.name }}</a></td>
                                    <td>{{ s_school.school_level.name }}</td>
                                    <td>{{ s_school.school_category.name }}</td>
                                    <td>{{ s_school.reg_time | time_format }}</td>
                                    {% if s_school.is_super %}
                                        <td>是</td>
                                    {% else %}
                                        <td>否</td>
                                    {% endif %}
                                    <td>
                                        <a href="{% url 'index:edit_school' %}?school_id={{ s_school.pk }}" class="btn btn-primary btn-xs">修改</a>
                                        <button class="del-btn btn btn-danger btn-xs" data-school-id="{{ s_school.pk }}">删除</button>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer">
                        <p class="page-info float-left">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</p>
                        <nav aria-label="Page navigation example">
                            <ul class="pagination float-right">
                                {# 首页 #}
                                <li class="page-item"><a class="page-link" href="?p=1{{ url_query }}"><<</a></li>
                                {# 上一页 #}
                                {% if not page_obj.has_previous %}
                                    <li class=" page-item disabled"><a class="page-link" href="javascript:void(0);">上一页</a></li>
                                {% else %}
                                    <li class="page-item"><a class="page-link" href="?p={{ page_obj.previous_page_number }}{{ url_query }}">上一页</a></li>
                                {% endif %}
                                {# 页码 #}
                                {# 前面的页码 #}
                                {% for left_page in left_pages %}
                                    <li class="page-item"><a class="page-link" href="?p={{ left_page }}{{ url_query }}">{{ left_page }}</a></li>
                                {% endfor %}
                                {# 当前的页码 #}
                                <li class="page-item active"><a class="page-link" href="?p={{ current_page }}{{ url_query }}">{{ current_page }}</a></li>
                                {# 后面的页码 #}
                                {% for right_page in right_pages %}
                                    <li class="page-item"><a class="page-link" href="?p={{ right_page }}{{ url_query }}">{{ right_page }}</a></li>
                                {% endfor %}
                                {# 下一页 #}
                                {% if not page_obj.has_next %}
                                    <li class=" page-item disabled"><a class="page-link" href="javascript:void(0);">下一页</a></li>
                                {% else %}
                                    <li class="page-item"><a class="page-link" href="?p={{ page_obj.next_page_number }}{{ url_query }}">下一页</a></li>
                                {% endif %}
                                {# 尾页 #}
                                <li class="page-item"><a class="page-link" href="?p={{ paginator.num_pages }}{{ url_query }}">>></a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}