academycity/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView


urlpatterns = [
    path('acauth/', include('apps.acauth.urls')),
    path('', include('apps.index.urls')),
    path('tinymce/', include('apps.tinymce.urls')),
    path('student/', include('apps.student.urls')),
    path('course/', include('apps.course.urls')),
    # 网站图标
    path('favicon.ico', RedirectView.as_view(url='/static/images/favicon.min.ico')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/acauth/urls.py
from django.urls import path
from . import views

app_name = 'acauth'

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('register/', views.Register.as_view(), name='register'),
    path('img_captcha/', views.image_captcha, name='img_captcha'),
    # path('operate_group/', views.operate_group, name='operate_group'),
    path('upload_avatar/', views.upload_avatar, name='upload_avatar'),
    path('logout/', views.logout_view, name='logout'),
]

apps/index/urls.py
from django.urls import path
from . import views

app_name = 'index'

urlpatterns = [
    path('', views.index, name='index'),
    path('school_list/', views.SchoolList.as_view(), name='school_list'),
    path('school_level/', views.school_level_view, name='school_level'),
    path('add_school/', views.AddSchool.as_view(), name='add_school'),
    path('edit_school/', views.EditSchool.as_view(), name='edit_school'),
    path('del_school/', views.del_school, name='del_school'),
    path('school_detail/<int:school_id>', views.school_detail, name='school_detail'),
    path('add_school_level/', views.add_school_level, name='add_school_level'),
    path('edit_school_level/', views.edit_school_level, name='edit_school_level'),
    path('del_school_level/', views.del_school_level, name='del_school_level'),
    path('upload_badge/', views.upload_badge_view, name='upload_badge'),
    path('join_school/', views.join_school_view, name='join_school'),
    path('quit_school/', views.quit_school_view, name='quit_school'),
    path('add_comment/', views.add_comment_view, name='add_comment_view'),
    path('director_list/', views.DirectorList.as_view(), name='director_list'),
    path('del_director/', views.del_director, name='del_director'),
    path('add_message/', views.add_message, name='add_message'),
    path('agree_apply_level/', views.agree_apply_level, name='agree_apply_level'),
    path('agree_apply_director/', views.agree_apply_director, name='agree_apply_director'),
    path('del_message/', views.del_message, name='del_message'),
]

apps/acauth/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from shortuuidfield import ShortUUIDField
from apps.index.models import School
from django.conf import settings
from apps.student.models import Superpower


class UserManager(BaseUserManager):
    def _create_user(self, telephone, email, username, password, **kwargs):
        if not telephone:
            raise ValueError('请输入手机号码！')
        if not email:
            raise ValueError('请输入邮箱！')
        if not username:
            raise ValueError('请输入用户名!')
        if not password:
            raise ValueError('请输入密码!')

        user = self.model(telephone=telephone, email=email, username=username, **kwargs)
        user.set_password(password)
        user.save()
        return user

    def create_user(self, telephone, email, username, password, **kwargs):
        kwargs['is_superuser'] = False
        return self._create_user(telephone, email, username, password, **kwargs)

    def create_superuser(self, telephone, email, username, password, **kwargs):
        kwargs['is_superuser'] = True
        kwargs['is_staff'] = True
        return self._create_user(telephone, email, username, password, **kwargs)


def get_superpower_default_id():
    default = 7
    return default


class User(AbstractUser):
    # 不使用默认的自增长的主键
    # 使用shortuuid
    # Shortuuidfield
    uid = ShortUUIDField(primary_key=True)
    telephone = models.CharField(max_length=11, unique=True)
    email = models.EmailField(unique=True, null=True)
    username = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)
    school = models.ForeignKey(School, on_delete=models.DO_NOTHING, null=True)
    avatar = models.URLField(default=settings.DEFAULT_USER_AVATAR)
    superpower = models.ForeignKey(Superpower, on_delete=models.DO_NOTHING, default=get_superpower_default_id, related_name='user_set')
    is_director = models.BooleanField(default=False)

    USERNAME_FIELD = 'telephone'
    # telephone, username, password
    REQUIRED_FIELDS = ['username', 'email']  # 当通过createsuperuser管理命令创建一个用户时，用于提示的一个字段名称列表
    EMAIL_FIELD = 'email'

    objects = UserManager()

    def get_full_name(self):
        return self.username

    def get_short_name(self):
        return self.username

apps/acauth/forms.py
from django import forms
from apps.forms import FormMixin
from django.core.cache import cache
from .models import User


class LoginForm(forms.Form, FormMixin):
    telephone = forms.CharField(max_length=11, min_length=11)
    password = forms.CharField(max_length=20, min_length=6, error_messages={'max_length': '密码最多不能超过20个字符!', 'min_length': '密码最少为6位！'})
    remember = forms.BooleanField(required=False)


class RegisterForm(forms.Form, FormMixin):
    username = forms.CharField(max_length=20)
    telephone = forms.CharField(max_length=11, min_length=11)
    email = forms.EmailField()
    password1 = forms.CharField(min_length=6, max_length=20, error_messages={'max_length': '密码最多不能超过20个字符!', 'min_length': '密码最少为6位！'})
    password2 = forms.CharField(min_length=6, max_length=20,error_messages={'max_length': '密码最多不能超过20个字符!', 'min_length': '密码最少为6位！'})
    img_captcha = forms.CharField(min_length=4, max_length=4)

    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()

        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')

        if password1 != password2:
            raise forms.ValidationError('两次密码输入不一致！')

        img_captcha = cleaned_data.get('img_captcha')
        if img_captcha:
            cached_img_captcha = cache.get(img_captcha.lower())
            if not cached_img_captcha or cached_img_captcha.lower() != img_captcha.lower():
                raise forms.ValidationError('图形验证码错误！')

        telephone = cleaned_data.get('telephone')
        tel_exists = User.objects.filter(telephone=telephone).exists()
        if tel_exists:
            raise forms.ValidationError('该手机号码已注册！')

        email = cleaned_data.get('email')
        email_exists = User.objects.filter(email=email).exists()
        if email_exists:
            raise forms.ValidationError('该邮箱已注册！')

apps/acauth/views.py
import os
from urllib import parse
from django.conf import settings
from django.contrib.auth.models import Group, Permission, ContentType
from django.shortcuts import render, HttpResponse, redirect, reverse
from django.views import View
from django.contrib.auth import login, logout, authenticate
from django.views.decorators.http import require_POST
from .forms import LoginForm, RegisterForm
from utils import restful
from io import BytesIO
from utils.captcha.accaptcha import Captcha
from django.core.cache import cache
from django.contrib.auth import get_user_model
from apps.index.models import School, SchoolLevel
from apps.course.models import Score, Course

User = get_user_model()


class Login(View):
    def get(self, request):
        if not hasattr(request, 'user') or not request.user.is_authenticated:
            return render(request, 'acauth/login.html')
        else:
            return redirect(reverse('index:index'))

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            telephone = form.cleaned_data.get('telephone')
            password = form.cleaned_data.get('password')
            remember = form.cleaned_data.get('remember')
            user = authenticate(request, telephone=telephone, password=password)
            if user:
                if user.is_active:
                    login(request, user)
                    if remember:
                        request.session.set_expiry(None)
                    else:
                        request.session.set_expiry(0)
                    return restful.ok()
                else:
                    return restful.unauth('您的账号已被冻结！')
            else:
                return restful.params_error('用户名或密码错误！')
        else:
            return restful.params_error(form.get_errors())


def logout_view(request):
    logout(request)
    return redirect(reverse('index:index'))


class Register(View):
    def get(self, request):
        if not hasattr(request, 'user') or not request.user.is_authenticated:
            return render(request, 'acauth/register.html')
        else:
            return redirect(reverse('index:index'))

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            telephone = form.cleaned_data.get('telephone')
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password1')
            user = User.objects.create_user(username=username, telephone=telephone, email=email, password=password)
            login(request, user)
            return restful.ok()
        else:
            return restful.params_error(form.get_errors())


def image_captcha(request):
    text, image = Captcha.gene_code()
    # BytesIO：相当于一个管道，用来存储图片的数据流
    out = BytesIO()
    # 调用image的save方法，将图片存储到BytesIO中
    image.save(out, 'png')
    # 将BytesIO文件的指针移动到最开始的位置
    out.seek(0)

    response = HttpResponse(content_type='image/png')
    # 从BytesIO的管道中，读取出图片数据，保存到response对象上
    response.write(out.read())
    # 文件指针跑到了最后面，tell()方法指出指针的位置，即文件的大小
    response['Content-length'] = out.tell()
    # 将验证码保存在缓存中
    cache.set(text.lower(), text.lower(), 5 * 60)

    return response


# 操作分组
# def operate_group(request):
#     # Group.objects.create(name='学生')
#     # group = Group.objects.filter(name='校级管理者').first()
#     # content_type = ContentType.objects.get_for_model(Score)
#     # permissions = Permission.objects.filter(content_type=content_type)
#     # group.permissions.set(permissions)
#     # group.save()
#     return HttpResponse('添加成功！')

@require_POST
def upload_avatar(request):
    file = request.FILES.get('file')
    print(file)
    name = file.name
    with open(os.path.join(settings.MEDIA_ROOT, name), 'wb') as fp:
        for chunk in file.chunks():
            fp.write(chunk)
    url = parse.unquote(request.build_absolute_uri(settings.MEDIA_URL + name))
    request.user.avatar = url
    request.user.save()
    return restful.ok()

front/templates/acauth/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Academy City | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'adminlte/plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="{% static 'adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!-- jQuery -->
    <script src="{% static 'adminlte/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'adminlte/dist/js/adminlte.min.js' %}"></script>
    <!-- ajax -->
    <script src="{% static 'js/acajax.min.js' %}"></script>
    <script src="{% static 'js/login.min.js' %}"></script>
    <!-- Sweetalter -->
    <script src="{% static 'js/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/acalert.min.js' %}"></script>
</head>
<body class="hold-transition login-page">
<div class="login-box">
    <div class="login-logo">
        <a href="{% url 'index:index' %}"><b>Academy</b>CITY</a>
    </div>
    <!-- /.login-logo -->
    <div class="card">
        <div class="card-body login-card-body">
            <p class="login-box-msg">立即登录开启超能力学习之旅!</p>

            <form action="" method="post">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <input type="text" class="form-control telephone" onkeyup="value=value.replace(/[^\d]/g,'')"
                           maxlength=11 placeholder="手机号码" name="telephone">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-user"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="password" class="form-control password" placeholder="密码" name="password">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-8">
                        <div class="icheck-primary">
                            <input type="checkbox" id="remember" name="remember">
                            <label for="remember">
                                记住我
                            </label>
                        </div>
                    </div>
                    <!-- /.col -->
                    <div class="col-4">
                        <button type="submit" class="btn btn-primary btn-block" id="login-btn">登录</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>
            <p class="mb-0">
                <a href="{% url 'acauth:register' %}" class="text-center">注册</a>
            </p>
        </div>
        <!-- /.login-card-body -->
    </div>
</div>
<!-- /.login-box -->
</body>
</html>

front/templates/acauth/register.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Academy City | Registration</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'adminlte/plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="{% static 'adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!-- css style -->
    <link rel="stylesheet" href="{% static 'css/acauth/register.min.css' %}">
    <!-- jQuery -->
    <script src="{% static 'adminlte/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'adminlte/dist/js/adminlte.min.js' %}"></script>
    <!-- ajax -->
    <script src="{% static 'js/acajax.min.js' %}"></script>
    <!-- Sweetalter -->
    <script src="{% static 'js/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/acalert.min.js' %}"></script>
    <!-- register js -->
    <script src="{% static 'js/register.min.js' %}"></script>
</head>
<body class="hold-transition register-page">
<div class="register-box">
    <div class="register-logo">
        <a href="../../index2.html"><b>Academy</b>CITY</a>
    </div>

    <div class="card">
        <div class="card-body register-card-body">
            <p class="login-box-msg">立即注册加入学园都市！</p>

            <form action="" method="post">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <input type="text" class="form-control username-input" placeholder="用户名">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-user"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="text" class="form-control telephone-input" placeholder="手机号码" onkeyup="value=value.replace(/[^\d]/g,'')" maxlength=11>
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-phone"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="email" class="form-control email-input" placeholder="邮箱">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-envelope"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="password" class="form-control password1-input" placeholder="密码">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="password" class="form-control password2-input" placeholder="确认密码">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="text" class="form-control captcha-input" placeholder="验证码">
                    <div class="input-group-append">
                        <div class="input-group-text">
                        </div>
                    </div>
                    <div class="img-captcha">
                        <img class="img-captcha-btn" src="{% url 'acauth:img_captcha' %}" alt="">
                    </div>
                </div>
                <div class="row">
                    <div class="col-8">
                        <a href="{% url 'acauth:login' %}" class="text-center">我已经拥有账户</a>
                    </div>
                    <div class="col-4">
                        <button type="submit" class="btn btn-primary btn-block" id="register-btn">注册</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>
        </div>
        <!-- /.form-box -->
    </div><!-- /.card -->
</div>
<!-- /.register-box -->
</body>
</html>